// Pages éditoriales et pages de confiance ajoutées après l'audit AdSense.
// Leur contenu reste statique afin d'être lisible sans JavaScript.

const date = '2026-09-13';

const PAGES_ADDITIONNELLES = [
  {
    slug: 'postes-rugby', court: 'Les postes', modifiee: date,
    titre: 'Les 15 postes du rugby : rôle, qualités et choix de carrière',
    description: 'Comprendre les quinze postes du rugby et choisir un profil cohérent pour commencer une carrière dans Destiny Rugby.',
    chapo: 'Le numéro porté dans le dos ne décrit pas seulement une place sur le terrain. Il détermine les courses, les duels, les responsabilités et les attributs qui comptent le plus dans une carrière.',
    suite: ['guide', 'saison-rugby', 'moteur', 'wiki/carriere-joueur'],
    blocs: [
      { h2: 'Première ligne : piliers et talonneur', id: 'premiere-ligne' },
      'Les piliers gauche et droit stabilisent la mêlée et travaillent dans les zones les plus denses. Leur carrière récompense la force, la résistance, le placement et la capacité à répéter les contacts. Le talonneur ajoute la précision du lancer en touche et intervient souvent comme premier soutien autour des regroupements.',
      'Dans Destiny Rugby, choisir la première ligne signifie accepter une progression moins spectaculaire à l’écran mais très influente sur la conquête. Un pilier qui tient sa mêlée, sécurise les rucks et reste disponible pendant quatre-vingts minutes peut peser davantage qu’un joueur accumulant les courses inutiles.',
      { h2: 'Deuxième et troisième lignes', id: 'avants-mobiles' },
      'Les deuxièmes lignes apportent taille, puissance et présence aérienne. Les troisièmes lignes couvrent davantage de terrain : plaquages, soutien, grattage et courses près de la défense. Le numéro 8 relie souvent la conquête au jeu courant et doit pouvoir avancer ballon en main.',
      'Ces postes conviennent à une carrière polyvalente. Une excellente note physique ne suffit pas : une forme basse ou une mauvaise discipline transforme vite l’activité en pénalités et en blessures. Le choix d’entraînement doit donc équilibrer puissance, endurance et technique.',
      { h2: 'La charnière : demi de mêlée et ouvreur', id: 'charniere' },
      'Le demi de mêlée accélère ou ralentit la sortie du ballon. L’ouvreur organise la circulation, choisit le jeu au pied et distribue vers les centres. Ils touchent beaucoup de ballons et leurs erreurs sont immédiatement visibles. Vision, passe, vitesse de décision et précision au pied structurent leur progression.',
      'Dans le moteur de match, la chaîne de passes part fréquemment du numéro 9 puis traverse le numéro 10. Ces postes offrent donc beaucoup d’occasions d’agir, mais aussi davantage de décisions sous pression. Ils sont adaptés aux joueurs qui veulent lire le terrain plutôt que chercher uniquement le duel physique.',
      { h2: 'Centres, ailiers et arrière', id: 'trois-quarts' },
      'Les centres doivent créer ou fermer des intervalles. Le premier centre joue souvent près de la défense ; le second dispose de davantage d’espace pour fixer et transmettre. Les ailiers terminent les mouvements et défendent une grande largeur. L’arrière couvre le fond du terrain, relance et répond au jeu au pied adverse.',
      'La vitesse aide, mais elle ne remplace ni le placement ni la sûreté technique. Un ailier isolé touche peu de ballons ; un arrière mal placé transforme un coup de pied ordinaire en occasion d’essai. Ces postes récompensent une construction équilibrée entre accélération, évitement, passe et défense.',
      { h2: 'Choisir sans chercher le poste parfait', id: 'choisir' },
      'Il n’existe pas de poste objectivement supérieur. Le bon choix est celui dont les actions correspondent au type de carrière recherché : conquête et travail collectif devant, organisation à la charnière, création et finition derrière. Le club de départ compte également, car la concurrence à ton poste détermine le temps de jeu.',
      { encadre: 'Avant de valider la création, compare ton niveau aux joueurs du même poste dans le club choisi. Une équipe prestigieuse offre un beau maillot, pas une place automatique.' },
    ],
  },
  {
    slug: 'saison-rugby', court: 'Une saison', modifiee: date,
    titre: 'Comment se déroule une saison dans Destiny Rugby',
    description: 'Calendrier, semaines de match, entraînement, forme, classement et intersaison : le déroulement complet d’une saison.',
    chapo: 'La semaine est l’unité de temps de la carrière. Chaque avance fait évoluer le calendrier, la condition du joueur, son club et les autres compétitions du monde.',
    suite: ['guide', 'blessures-recuperation', 'transferts-contrats', 'pyramide'],
    blocs: [
      { h2: 'Préparer plutôt que cliquer trop vite', id: 'preparer' },
      'Avant chaque avance, vérifie la forme, le moral, l’entraînement actif et la prochaine rencontre. Une semaine paraît courte, mais certaines décisions produisent des effets pendant plusieurs mois : surcharge physique, promesse au club, négociation ou réponse publique.',
      'Le calendrier ne se limite pas au championnat. Les coupes, sélections et périodes sans match créent des rythmes différents. Une semaine libre peut servir à récupérer ; une série de rencontres impose parfois de renoncer à une progression immédiate pour préserver la saison entière.',
      { h2: 'Le jour de match', id: 'match' },
      'Lorsque le joueur est sélectionné, le match peut être suivi en direct. Le moteur place trente joueurs sur un terrain mesuré en mètres et ralentit quand une action concerne le personnage. Les intentions demandées ne garantissent jamais le résultat : elles sont arbitrées par les attributs, la fatigue, le placement et l’opposition.',
      'La note ne récompense pas seulement les essais. Un avant peut construire sa performance par les plaquages et la conquête ; un demi par la distribution ; un arrière par la couverture et les relances. Chercher la même statistique à tous les postes produit une carrière incohérente.',
      { h2: 'Classement et temps de jeu', id: 'classement' },
      'Le championnat avance journée après journée pour tous les clubs. La réputation du personnage ne lui offre pas un statut permanent : la concurrence interne, la forme et les performances récentes influencent encore les sélections. Une place perdue peut être reprise, mais rarement en accumulant les semaines à faible condition.',
      'Les divisions amateurs jouent selon un calendrier plus continu tandis que les niveaux supérieurs concentrent davantage les enjeux. Les montées et descentes modifient réellement la difficulté de la saison suivante.',
      { h2: 'Le bilan de fin de saison', id: 'bilan' },
      'À l’intersaison, le jeu rassemble les performances, les titres, la progression et la situation contractuelle. C’est le moment où une bonne saison devient une hausse de niveau, une nouvelle offre ou une sélection. Une saison moyenne n’efface pas une carrière, mais plusieurs années sans temps de jeu ferment progressivement les meilleures portes.',
      { h2: 'Construire sur plusieurs années', id: 'long-terme' },
      'Une carrière peut durer quinze saisons ou davantage selon l’âge de départ et les événements. Le meilleur plan n’est donc pas d’optimiser chaque semaine isolément. Il faut conserver une marge physique, choisir des clubs où jouer et accepter qu’une blessure ou un transfert raté change l’histoire prévue.',
      { encadre: 'Une sauvegarde avant chaque décision enlèverait tout poids au récit. Le jeu est conçu pour que les saisons imparfaites fassent partie de la carrière.' },
    ],
  },
  {
    slug: 'transferts-contrats', court: 'Transferts', modifiee: date,
    titre: 'Transferts et contrats : construire une carrière cohérente',
    description: 'Comprendre les offres, la concurrence, la durée des contrats et les choix de club dans le RPG Destiny Rugby.',
    chapo: 'Un transfert réussi ne consiste pas toujours à rejoindre le club le plus prestigieux. Le temps de jeu, le poste, la division et la durée du contrat peuvent compter davantage que le nom affiché sur le maillot.',
    suite: ['wiki/carriere-joueur', 'saison-rugby', 'pyramide', 'guide'],
    blocs: [
      { h2: 'Pourquoi les offres n’arrivent pas immédiatement', id: 'offres' },
      'Les clubs observent d’abord la situation contractuelle. Un joueur lié pour plusieurs saisons n’est pas abordé comme un joueur proche de la fin de son engagement. Au début d’une carrière, il est donc normal de ne recevoir aucune proposition pendant un certain temps.',
      'La réputation, le niveau, la forme et les performances rendent une candidature crédible, mais elles ne suppriment pas les contraintes du marché. Une bonne année prépare parfois l’offre de l’année suivante plutôt qu’un départ instantané.',
      { h2: 'Lire un effectif avant de signer', id: 'effectif' },
      'Regarde combien de joueurs occupent ton poste, leur niveau et leur âge. Rejoindre une équipe supérieure pour devenir troisième choix peut ralentir davantage la progression que rester titulaire un étage plus bas. À l’inverse, un effectif vieillissant peut ouvrir une place rapidement.',
      'La division fixe aussi le niveau moyen des adversaires. Monter trop tôt augmente la difficulté de chaque duel ; rester trop longtemps sans ambition réduit les occasions de titres et de sélection. Le transfert est un compromis sportif, pas une simple amélioration linéaire.',
      { h2: 'Négocier sans perdre le projet sportif', id: 'negocier' },
      'La durée donne de la sécurité mais retarde le prochain passage sur le marché. Un contrat court laisse davantage de liberté, avec le risque de se retrouver sans solution après une mauvaise saison. Le salaire participe au récit et au palmarès économique, mais il ne doit pas masquer le rôle promis.',
      'Les échanges passent par le réseau social interne : clubs et agents y écrivent directement. Ignorer la messagerie peut donc faire manquer une occasion, même lorsque la carrière semble calme sur l’écran principal.',
      { h2: 'Partir, rester ou descendre', id: 'decision' },
      'Rester permet de consolider une place et de poursuivre une histoire collective. Partir offre un nouvel environnement et une concurrence différente. Descendre volontairement peut être rationnel après une longue période sur le banc : retrouver des minutes vaut parfois mieux qu’un prestige inutilisé.',
      { h2: 'Après la dernière signature', id: 'retraite' },
      'La fin d’un contrat n’impose pas automatiquement la retraite, mais l’âge, l’état physique et les offres disponibles rendent chaque prolongation plus difficile. La carrière conserve les clubs traversés, les statistiques et les titres : une dernière saison modeste peut donner une conclusion plus juste qu’une sortie uniquement dictée par la note générale.',
      { encadre: 'Avant de signer, réponds à trois questions : vais-je jouer, ce niveau correspond-il à mon joueur, et quelle porte ce contrat laissera-t-il ouverte ensuite ?' },
    ],
  },
  {
    slug: 'blessures-recuperation', court: 'Blessures', modifiee: date,
    titre: 'Blessures, fatigue et récupération au fil d’une carrière',
    description: 'Gérer la forme, les charges d’entraînement, les blessures et le retour au jeu dans Destiny Rugby.',
    chapo: 'La condition physique n’est pas une réserve que l’on vide sans conséquence. Matchs, entraînement, âge et historique médical se combinent, puis déterminent la disponibilité et la qualité des actions.',
    suite: ['saison-rugby', 'postes-rugby', 'guide', 'wiki/carriere-joueur'],
    blocs: [
      { h2: 'Différencier forme et blessure', id: 'forme' },
      'Une forme basse réduit la capacité à répéter les efforts sans signifier que le joueur est blessé. Une blessure possède au contraire une durée et peut rendre indisponible. Jouer fatigué augmente le risque et dégrade les décisions bien avant l’arrêt complet.',
      'La récupération converge vers une condition de base liée notamment à l’endurance et à l’âge. Elle n’est donc ni instantanée ni identique pour tout le monde. Deux joueurs soumis au même calendrier peuvent arriver au printemps dans des états très différents.',
      { h2: 'La charge d’entraînement', id: 'entrainement' },
      'L’entraînement fait progresser un secteur, mais son bénéfice doit être comparé au calendrier. Ajouter de la charge pendant une série de matchs difficiles peut coûter davantage en disponibilité que ce qu’elle rapporte en attribut. Les semaines plus calmes sont les meilleurs moments pour travailler intensément.',
      'Pour un entraîneur, le problème devient collectif : les avants encaissent davantage de contacts, les joueurs rapides exposent les muscles des jambes et les remplaçants ont besoin de rythme sans pouvoir tous commencer le même match.',
      { h2: 'Revenir sans brûler une étape', id: 'retour' },
      'La fin de l’indisponibilité ne signifie pas automatiquement une condition maximale. Le retour doit tenir compte de la concurrence et de la prochaine série de rencontres. Reprendre immédiatement toutes les responsabilités peut provoquer une mauvaise performance et faire perdre la place que l’on voulait récupérer.',
      { h2: 'L’âge change le calcul', id: 'age' },
      'Un jeune joueur possède davantage de temps pour reconstruire sa progression après un arrêt. En fin de carrière, chaque absence occupe une part plus importante des saisons restantes. Cela ne rend pas les vétérans inutiles : leur niveau et leur expérience peuvent compenser, mais la gestion du calendrier devient centrale.',
      { h2: 'Accepter l’imprévu', id: 'imprevu' },
      'Les blessures empêchent une carrière de devenir une simple suite de hausses statistiques. Elles obligent à choisir entre patience, retour accéléré, changement de club ou nouvelle façon de jouer. Le système reste lisible : l’état, la durée et les conséquences apparaissent dans la fiche et le calendrier.',
      { encadre: 'Le meilleur moyen de préserver une saison est souvent d’abandonner une semaine parfaite. La récupération fait partie de la stratégie, elle n’est pas une punition entre deux matchs.' },
    ],
  },
  {
    slug: 'a-propos', court: 'À propos', legal: true, noAds: true, modifiee: date,
    titre: 'À propos de Destiny Rugby',
    description: 'Origine, ligne éditoriale et fonctionnement du projet indépendant Destiny Rugby.',
    chapo: 'Destiny Rugby est un projet indépendant consacré à la carrière d’un rugbyman, de ses débuts à sa retraite, dans un monde sportif simulé saison après saison.',
    blocs: [
      { h2: 'Le projet', id: 'projet' },
      'Le jeu cherche à raconter ce qui se passe entre les résultats : concurrence à un poste, forme, blessures, contrats, choix personnels et conséquences à long terme. Il est jouable gratuitement dans un navigateur sur ordinateur ou mobile.',
      { h2: 'Une documentation écrite pour le jeu', id: 'editorial' },
      'Les guides publiés sur ce site sont rédigés et vérifiés à partir des règles, données et bancs d’essai du projet. Ils ne recopient pas des articles externes. Lorsqu’un chiffre décrit le moteur, il provient d’une mesure reproductible utilisée pendant le développement.',
      { h2: 'Indépendance', id: 'independance' },
      'Destiny Rugby n’est affilié à aucune fédération, ligue, compétition ou club. Les noms et signes distinctifs appartiennent à leurs détenteurs respectifs. Les éventuelles annonces servent à contribuer aux frais d’hébergement et restent séparées des décisions de jeu.',
    ],
  },
  {
    slug: 'confidentialite', court: 'Confidentialité', legal: true, noAds: true, modifiee: date,
    titre: 'Politique de confidentialité et cookies',
    description: 'Données locales, services en ligne, mesure d’audience, publicité et droits des utilisateurs de Destiny Rugby.',
    chapo: 'Cette page explique quelles données peuvent être utilisées par Destiny Rugby, dans quel but et quels choix sont proposés aux visiteurs.',
    blocs: [
      { h2: 'Sauvegardes locales', id: 'local' },
      'La carrière solo et les préférences sont principalement enregistrées dans le stockage local du navigateur. Elles restent sur l’appareil tant que l’utilisateur ne les efface pas. Supprimer les données du site depuis le navigateur retire ces sauvegardes locales.',
      { h2: 'Fonctions en ligne', id: 'en-ligne' },
      'La ligue privée et les notifications nécessitent des données techniques côté serveur, notamment un identifiant de session, les éléments nécessaires au fonctionnement de la ligue et, si l’utilisateur l’active, un abonnement de notification. Les cookies de session sont utilisés pour maintenir la connexion et sécuriser les actions.',
      { h2: 'Mesure d’audience', id: 'mesure' },
      'Le site utilise Vercel Analytics et peut utiliser Google Tag Manager pour comprendre les pages consultées et les étapes générales du parcours. Les événements prévus ne contiennent pas le nom du personnage, son club ni le texte libre écrit au Maître du Jeu. Les stockages Google sont refusés par défaut jusqu’au choix de consentement applicable.',
      { h2: 'Publicité Google', id: 'publicite' },
      'Si AdSense est activé après validation du site et consentement, Google et ses partenaires peuvent utiliser des cookies pour diffuser, mesurer et personnaliser des annonces selon les choix de l’utilisateur. La personnalisation peut être désactivée dans les paramètres des annonces Google. Aucune annonce display n’est placée dans l’interface du jeu.',
      { h2: 'Services techniques', id: 'services' },
      'L’hébergement est fourni par Vercel. Certaines réponses libres adressées au Maître du Jeu peuvent être transmises au fournisseur d’intelligence artificielle configuré afin de produire la réponse demandée. Il ne faut pas saisir d’information personnelle sensible dans ces champs libres.',
      { h2: 'Vos choix et demandes', id: 'droits' },
      'L’utilisateur peut refuser la publicité, vider le stockage local et désactiver les notifications depuis son navigateur. Pour une question d’accès, de rectification ou de suppression concernant un service en ligne, il peut écrire à [destiny.rugby.fr@gmail.com](mailto:destiny.rugby.fr@gmail.com).',
      { encadre: 'Dernière mise à jour : 13 septembre 2026. Cette politique sera mise à jour lorsqu’un fournisseur ou un usage de données change.' },
    ],
  },
  {
    slug: 'mentions-legales', court: 'Mentions légales', legal: true, noAds: true, modifiee: date,
    titre: 'Mentions légales',
    description: 'Informations relatives à l’édition et à l’hébergement du site Destiny Rugby.',
    chapo: 'Destiny Rugby est un site et un jeu web indépendant accessible à l’adresse www.destiny-rugby.fr.',
    blocs: [
      { h2: 'Édition et publication', id: 'edition' },
      'Le site est édité à titre indépendant sous le nom **Destiny Rugby** par **Colin Gomez**, responsable de la publication. Adresse : **81 rue des Arcs, quartier Saint-Cyprien, 31300 Toulouse, France**. Contact : [destiny.rugby.fr@gmail.com](mailto:destiny.rugby.fr@gmail.com).',
      { h2: 'Hébergement', id: 'hebergement' },
      'Le site est hébergé par **Vercel Inc.** Les informations actualisées concernant l’entreprise et son infrastructure sont disponibles sur [vercel.com](https://vercel.com).',
      { h2: 'Propriété intellectuelle', id: 'propriete' },
      'Les textes propres au site, son code, ses interfaces et ses créations originales sont protégés. Les noms de clubs, de compétitions et de joueurs ainsi que leurs signes distinctifs appartiennent à leurs détenteurs respectifs. Leur présence ne signifie aucune affiliation ni approbation.',
      { h2: 'Responsabilité', id: 'responsabilite' },
      'Le contenu du jeu est une simulation à vocation de divertissement. Malgré les vérifications, une erreur ou une indisponibilité temporaire peut survenir. Toute demande de correction peut être transmise par l’adresse de contact.',
    ],
  },
  {
    slug: 'contact', court: 'Contact', legal: true, noAds: true, modifiee: date,
    titre: 'Contacter Destiny Rugby',
    description: 'Contacter l’équipe Destiny Rugby pour une question, un signalement ou l’exercice de droits relatifs aux données.',
    chapo: 'Une question sur le jeu, un contenu à corriger ou une demande concernant vos données peut être adressée directement à l’équipe du projet.',
    blocs: [
      { h2: 'Adresse de contact', id: 'adresse' },
      'Écrivez à [destiny.rugby.fr@gmail.com](mailto:destiny.rugby.fr@gmail.com) en précisant l’objet de la demande. N’envoyez jamais de mot de passe, de code de connexion ni de donnée médicale ou financière.',
      { h2: 'Signaler un problème', id: 'probleme' },
      'Pour un problème technique, indiquez la page concernée, l’appareil et le navigateur utilisés ainsi que les étapes permettant de reproduire le problème. Une capture peut aider, à condition qu’elle ne contienne aucune information personnelle.',
      { h2: 'Données personnelles', id: 'donnees' },
      'Pour une demande d’accès, de rectification ou de suppression, utilisez l’objet « Données personnelles ». Une vérification raisonnable de l’identité liée au compte peut être demandée sans jamais réclamer votre mot de passe.',
    ],
  },
];

module.exports = { PAGES_ADDITIONNELLES };
