// Notes calibrées À LA MAIN pour les joueurs identifiés (internationaux, cadres).
// La base `base_rugby_finale.json` fournit du temps de jeu et des essais, mais
// rien qui distingue un pilier international d'un pilier honnête qui joue
// autant : ces notes corrigent le tir sur les joueurs qu'on connaît.
// Format : 'Nom PRÉNOM': note (l'âge vient toujours de la base réelle).

// ---------------- FRANCE (Top 14 / Pro D2) ----------------
const VEDETTES_FRANCE = {
  // Stade Toulousain
  'Antoine DUPONT': 95, 'Romain NTAMACK': 90, 'Thomas RAMOS': 89,
  'Emmanuel MEAFOU': 88, 'Cyril BAILLE': 88, 'Blair KINGHORN': 88,
  'Jack WILLIS': 89, 'Julien MARCHAND': 87, 'Thibaud FLAMENT': 87,
  'Francois CROS': 87, 'Ange CAPUOZZO': 87, 'Peato MAUVAKA': 86,
  'Juan cruz MALLIA': 86, 'Tommaso MENONCELLO': 86, 'Anthony JELONCH': 85,
  'Santiago CHOCOBARES': 85, 'Matthis LEBEL': 84, 'Dorian ALDEGHERI': 84,
  'Alexandre ROUMAT': 84, 'Joshua BRENNAN': 83, 'Pierre-louis BARASSI': 83,
  'Georges henri COLOMBE REAZEL': 83, 'Teddy THOMAS': 81, 'Rodrigue NETI': 81,
  'Paul GRAOU': 80, 'David AINUU': 80, "David AINU'U": 80,
  // Stade Français Paris
  'Sekou MACALOU': 84, 'Tawera KERR BARLOW': 84, 'Ihaia WEST': 83,
  'Yoan TANGA MANGENE': 83, 'Giacomo NICOTERA': 82, 'Paul GABRILLAGUES': 82,
  'Thierry PAIVA': 81, 'Giorgi MELIKIDZE': 81, 'Louis CARBONEL': 80,
  'Paul ALO EMILE': 80, 'Tani VILI': 80, 'Jérémy charles WARD': 80,
  'Peniasi DAKUWAQA': 80, 'Paul ABADIE': 79, 'Samuel EZEALA': 79,
  'Setareki TURAGACOKE': 78, 'Romain BRIATTE': 78, 'Lester ETIEN': 78,
  'Sergo ABRAMISHVILI': 78,
  // Racing 92
  'Josua TUISOVA': 88, 'Vinaya HABOSI': 84, 'Demba BAMBA': 84,
  'Romain TAOFIFENUA': 83, 'Joseph MANU': 86, 'Nathan HUGHES': 82,
  'Ibrahim DIALLO': 82, 'Lekima vuda TAGITAGIVALU': 82, 'Jordan JOSEPH': 81,
  'Antoine GIBERT': 80, 'Max SPRING': 80, 'Maxime MACHENAUD': 78,
  'Paul COSTES': 79, 'Hassane KOLINGAR': 79, 'Guram GOGICHASHVILI': 79,
  'Wame NAITUVI': 79, 'Leo CARBONNEAU': 79, 'Wilfried HULLEU': 79,
  'Selesitino RAVUTAUMADA': 80, 'Daniel TUPOU': 79, 'Josaia RALULU': 78,
  'Taniela TUPOU': 84,
  // Montpellier HR
  'Stuart HOGG': 84, 'Adam BEARD': 83, 'Langi GLEESON': 83,
  'Reda WARDI': 84, 'Arthur VINCENT': 82, 'Adam HASTINGS': 82,
  'Florian VERHAEGHE': 81, 'Lenni NOUCHI': 81, 'Yacouba CAMARA': 80,
  'Christopher TOLOFUA': 80, 'Mohamed HAOUAS': 80, 'Bastien CHALUREAU': 79,
  'Sebastien BEZY': 79, 'Alexandre BECOGNEE': 79, 'Gabriel NGANDEBE': 79,
  'Dimitri DELIBES': 79, 'Wilfrid HOUNKPATIN': 79, 'Tom BANKS': 81,
  'Ricky RICCITELLI': 80, 'Jordan UELESE': 80, 'Ruben VAN HEERDEN': 80,
  'Alistaire PRICE': 79, 'Viliami VUNIPOLA': 79, 'Justo PICCARDO': 79,
  'Mickael CAPELLI': 78,
  // Stade Rochelais
  'Grégory ALLDRITT': 90, 'William SKELTON': 88, 'Jonathan DANTY': 85,
  'Nolann LE GARREC': 85, 'Oscar JEGOU': 84, 'Paul BOUDEHENT': 84,
  'Antoine HASTOY': 83, 'Pierre BOURGARIT': 83, 'Salmaan MOERAT': 84,
  'Dillyn LEYDS': 82, 'Jack NOWELL': 82, 'Davit NINIASHVILI': 83,
  'George MOALA': 81, 'Levani botia VEIVUKE': 83, 'Thomas LAVAULT': 80,
  'Ulupano SEUTENI': 80, 'Thomas BERJON': 79, 'Quentin LESPIAUCQ': 79,
  'Ben HEALY': 81, 'Andy TIMO': 78, 'Jules FAVRE': 78,
  // Union Bordeaux Bègles
  'Louis BIELLE-BIARREY': 91, 'Damian PENAUD': 89, 'Matthieu JALIBERT': 86,
  'Maxime LUCU': 84, 'Yoram FALATEA MOEFANA': 85,
  'Nicolas DEPOORTERE': 84, 'Cameron WOKI': 83, 'Jefferson POIROT': 83,
  'Benjamin TAMEIFUNA': 84, 'Thomas daniel WILLIS': 82, 'Pablo UBERTI': 82,
  'Romain BUROS': 81, 'Maxime LAMOTHE': 81, 'Cyril CAZEAUX': 80,
  'Sipili FALATEA': 80, 'Adam COLEMAN': 80, 'Daniël michael DU PLESSIS': 83,
  'Jean-lue DU PREEZ': 81, 'Gaëtan BARLOT': 79, 'Marko GAZZOTTI': 79,
  'Arthur RETIERE': 79, 'Martin PAGE RELO': 79, 'Salesi RAYASI': 79,
  'Röhan JANSE VAN RENSBURG': 79, 'Boris PALU': 78,
  // Section Paloise
  'Emilien GAILLETON': 84, 'Théo ATTISSOGBE': 84, 'Beka GORGADZE': 82,
  'Juliàn sixto MONTOYA': 85, 'Facundo ISA': 82, 'Joe SIMMONDS': 82,
  'Thomas JOLMES': 80, 'Daniel BIBI BIZIWU': 80, 'Lekso KAULASHVILI': 80,
  'Baptiste PESENTI': 79, 'Thibault DAUBAGNA': 78,
  'Rodrigo DE BIVAR WEINHOLTZ CARDOSO MARTA': 81, 'Aaron GRANDIDIER-NKANANG': 79,
  'Bastien VERGNES TAILLEFER': 78, 'Thomas LACLAYAT': 78, 'Clément LAPORTE': 78,
  // ASM Clermont Auvergne
  'Marcos KREMER': 86, 'Baptiste JAUNEAU': 83, 'Alivereti RAKA': 82,
  'Pita-gus SOWAKULA': 82, 'Killian TIXERONT': 81, 'Darcy SWAIN': 81,
  'Bautista DELGUY': 80, 'Cristian OJOVAN': 80, 'Giorgi AKHALADZE': 79,
  'Selevasio TOLOFUA': 79, 'Régis MONTAGNE': 79, 'Kylan HAMDAOUI': 79,
  'Etene NANAI SETURO': 79, 'Alexander james LAM': 79, 'Thibaud LANEN': 78,
  'Alivereti LOALOA': 78, 'Harrison PLUMMER': 78,
  // Aviron Bayonnais
  'Arthur ITURRIA': 83, 'Mateo CARRERAS': 85, 'Rodrigo BRUNI': 82,
  'Herschel JANTJIES': 82, 'Killian GERACI': 81, 'Federico MORI': 81,
  'Léo COLY': 81, 'Joris SEGONDS': 80, 'Sireli MAQALA': 82,
  'Alexandre FISCHER': 80, 'Madosha TAMBWE': 80, 'Tevita TATAFU': 79,
  'Facundo BOSCH': 79, 'Emerick SETIANO': 79, 'Robert james DU PREEZ': 79,
  'Etuale manusamoa TUILAGI': 79, 'Robert LEOTA': 79, 'Luke TAGI': 78,
  'Baptiste HEGUY': 78, 'Guillaume MARTOCQ': 78,
  // Lyon OU
  'Baptiste COULLOUD': 83, 'Baptiste COUILLOUD': 83, 'Dylan CRETIN': 82,
  'Mickaël GUILLARD': 83, 'Ethan DUMORTIER': 82, 'Jiuta naqoli WAINIQOLO': 84,
  'Samuel SIMMONDS': 83, 'Sanele NOHAMBA': 82, 'Thomas GALLO': 82,
  'Monty IOANE': 81, 'Léo BERDEU': 81, 'Beka SAGINADZE': 81,
  'Félix LAMBEY': 80, 'Camille CHAT': 80, 'Thibaut REGARD': 79,
  'Josiah meihana MARAKU': 79, 'Liam robson ALLEN': 79, 'Fousseynou CISSOKHO': 78,
  'David patrick JACKSON': 79, 'Irakli APTSIAURI': 78,
  // RC Toulon
  'Charles OLLIVON': 88, 'Gael FICKOU': 86, 'Jean baptiste GROS': 85,
  'Baptiste SERIN': 83, 'Zach yvan MERCER': 84, 'Kyle SINCKLER': 84,
  'Gabin VILLIERE': 82, 'Melvyn JAMINET': 81, 'Lewis wesley LUDLAM': 82,
  'Juan ignacio BREX': 83, 'Tomas ALBORNOZ': 82, 'Huw JONES': 83,
  'Beka GIGASHVILI': 81, 'Dany PRISO MOUANGUE': 80, 'Setariki TUICUVU': 80,
  'Rabah SLIMANI': 79, 'Swan REBBADJ': 80, 'David george RIBBANS': 81,
  'Gianmarco LUCCHESI': 80, 'Teddy BAUBIGNY': 79, 'Antoine FRISCH': 80,
  'Benjamin WHITE': 80, 'Judicael CANCORIET': 78, 'Esteban ABADIE': 78,
  // Castres Olympique
  'Mathieu BABILLOT': 80, 'Paul JEDRASIAK': 79, 'Vilimoni BOTITU': 81,
  'Santiago ARATA PERRONE': 81, 'Dalton PAPALII': 85, 'Abraham PAPALII': 80,
  'Hamish WATSON': 82, 'Levan CHILACHAVA': 78, 'Geoffrey PALIS': 78,
  'Taylor GONTINEAC': 79, 'Remy BAGET': 78, 'Elias jack GOODHUE': 79,
  'Florent VANVERBERGHE': 78, 'Thomas STANIFORTH': 78, 'William COLLIER': 78,
  'Adrea COCAGI': 78, 'Vuate KARAWALEVU': 78,
  // USA Perpignan
  'Paolo GARBISI': 85, 'Posolo TUILAGI': 83, 'Sevu REECE': 85,
  'Jeronimo DE LA FUENTE': 81, 'Peceli YATO': 81, 'Joaquin OVIEDO': 81,
  'Luke MCGRATH': 81, 'Braydon ENNOR': 82, 'Marco RICCIONI': 81,
  'Benjamin URDAPILLETA': 79, 'Pietro CECCARELLI': 79, 'Cedate GOMES SA': 79,
  'Jake aron MCINTYRE': 79, 'Jacobus VAN TONDER': 78, 'Setareki TOGANIYADRAVA': 79,
  'Lachlan william SWINTON': 79, 'Jonathan GRAY': 79, 'Lucas DUBOIS': 78,
  // RC Vannes
  'Anthony BOUTHIER': 80, 'Sione KALAMAFONI': 80, 'Matias ALEMANNO': 81,
  'Santiago MEDRANO': 80, 'Michael RURU': 78, 'Eliott ROUDIL': 78,
  'Nathanael HULLEU': 78, 'Mikheil ALANIA': 78, 'Edoardo IACHIZZI': 78,
  'Inia TABUAVOU': 78, 'Simione KURUVOLI': 79, 'Millenium SANERIVI': 78,
  'Francisco GORRISSEN': 78, 'Joe JONAS': 77, 'David CHERRY': 77,
  // ---------------- PRO D2 ----------------
  'Arno BOTHA': 78, 'Liam TURNER': 74, 'Dylan JAMINET': 73,
  'Shaun REYNOLDS': 72, 'Johan georg WASSERMAN': 71, 'Rati ZAZADZE': 71,
  'John COONEY': 78, 'Stuart OLDING': 76, 'Curwin BOSCH': 76,
  'Marcel VAN DER MERWE': 74, 'Aymeric LUC': 74, 'Christian james JUDGE': 73,
  'Simote MOALA': 73, 'Georges SHVELIDZE': 72, 'Maxime SIDOBRE': 72,
  'Asaeli TUIVUAKA': 72, 'James SHILLCOCK': 72, 'Vakhtang ABDALADZE': 72,
  'Konstantine MIKAUTADZE': 72, 'Etonia durugalo BAINIVALU': 71,
  'Izack RODDA': 79, 'Albert TUISUE': 76, 'Tyler ARDRON': 75,
  'Teimana HARRISON': 74, 'Caleb MUNTZ': 74, 'Tornike JALAGONIA': 73,
  'Sébastien TAOFIFENUA': 72, 'Kapeliele PIFELETI JR': 72,
  'Joel KPOKU': 78, 'Francis SAILI': 75, 'Adrian MOTOC': 73,
  'Evan OLMSTEAD': 73, 'Vincent RATTEZ': 73, 'Owen WILLIAMS': 73,
  'Tyler MORGAN': 72, 'Guillaume ROUET': 72, 'Bautista EZCURRA': 71,
  'Hayden THOMPSON-STRINGER': 71,
  'Sione langi VAILANU': 76, 'Duncan PAIA’AUA': 75, "Duncan PAIA'AUA": 75,
  'Yann LESGOURGUES': 72, 'Arthur BONNEVAL': 72, 'Alban PLACINES': 72,
  'Raynard ROETS': 72, 'Kylian JAMINET': 71,
  'Uzair CASSIEM': 76, 'Mayco VIVAS': 76, 'Vano KARKADZE': 76,
  'Vasil LOBZHANIDZE': 74, 'Alex NEWSOME': 74, 'Luka MATKAVA': 73,
  'Danny TOALA': 72, 'Jonathan RURU': 72, 'Ratu leone ROTUISOLIA': 71,
  'Thomas FORTUNEL': 74, 'Hugo ZABALZA': 73, 'Enzo HERVE': 73,
  'Lewis BEAN': 72, 'Lucio SORDONI': 72, 'Jack william WALSH': 72,
  'Tevita ROKOSUKA': 72, 'Yvan REILHAC': 71, 'Fred QUERCY': 71,
  'Samuel DAVIES': 74, 'Raffaele COSTA STORTI': 74, 'Lucas TAUZIN': 73,
  'Fergus LEE WARNER': 73, 'Julien HERITEAU': 72, 'Barnabé COUILLOUD': 72,
  'Romain RUFFENACH': 71, 'Eric ESCANDE': 71, 'Charlton HOLWILL': 71,
  'Federico ignacio LAVANINI': 75, 'Richard HARDWICK': 72,
  'Guillaume TARTAS': 72, 'Myles EDWARDS': 71, 'Martin ALONSO MUÑOZ': 71,
  'Malakai fonokalafi FEKITOA': 76, 'Charly MALIE': 72,
  'Killian TAOFIFENUA': 71, 'Mackenzie MARTIN': 71, 'Shahn ERU': 71,
  'Santiago SOCINO': 74, 'Enrique PIERETTO HEILAND': 73,
  'William DEMOTTE': 72, 'Sialevailea TOLOFUA': 72, 'Craig WILLIS': 71,
  'Louis DUPICHOT': 71, 'Taniela MATAKAIONGO': 71,
  'Aphiwe DYANTYI': 74, 'Facundo POMPONIO': 72, 'Apisai NAQALEVU': 72,
  'Solomon ALAIMALO': 72, 'Caleb kalisi TIMU': 72, 'Ruben SCHOEMAN': 71,
  'Benjamin BOTICA': 74, 'Gela APRASIDZE': 73, 'Matthew BEUKEBOOM': 72,
  'Pone FAAMAUSILI': 72, 'Peter LYDON': 71,
  'Tedo ABZHANDADZE': 74, 'Eoghan gerard MASTERSON': 71,
  "Benjamin O'DONNELL": 71, 'Ronald PIETERS': 70, 'Karsen TALALUA': 70,
  'Nephi LEATIGAGA': 72, 'David LOLOHEA': 71, 'Jean baptiste BARRERE': 70,
  'Charles MATTHEWS': 70,
  'Xavier MIGNOT': 72, 'Marco TAULEIGNE': 72, 'Ratu osea WAQANINAVATU': 71,
};

// ---------------- MONDE (Premiership, URC, Super Rugby, League One…) ----------
// Tous ces noms ont été vérifiés présents dans base_rugby_finale.json.
const VEDETTES_MONDE = {
  // Super Rugby Pacific / All Blacks & Wallabies
  'Ardie SAVEA': 92, 'Will JORDAN': 90, 'Jordie BARRETT': 89,
  'Beauden BARRETT': 87, 'Codie TAYLOR': 86, 'Scott BARRETT': 88,
  'Damian MCKENZIE': 86, 'Caleb CLARKE': 84, 'Sevu REECE': 85,
  'Tamaiti WILLIAMS': 85, 'Tyrel LOMAX': 85, 'Asafo AUMUA': 82,
  'Wallace SITITI': 85, 'Peter LAKAI': 81, 'Warner DEARNS': 83,
  'Rob VALETINI': 88, 'Nick FROST': 84, 'Fraser MCREIGHT': 85,
  'Harry POTTER': 80, 'Tom LYNAGH': 78,
  // Premiership / XV de la Rose
  'Maro ITOJE': 90, 'Ellis GENGE': 86, 'Tom CURRY': 87, 'Ben EARL': 85,
  'Marcus SMITH': 85, 'Fin SMITH': 84, 'Alex MITCHELL': 85,
  'Tommy FREEMAN': 86, 'Ollie LAWRENCE': 85, 'Immanuel FEYI-WABOSO': 84,
  'Freddie STEWARD': 83, 'Henry POLLOCK': 84, 'Jamie GEORGE': 83,
  'Will STUART': 82, 'George FORD': 83, 'Owen FARRELL': 83,
  'Elliot DALY': 81, 'Chandler CUNNINGHAM-SOUTH': 82, 'Alex COLES': 82,
  'Tom WILLIS': 83, 'Theo DAN': 81, 'Joe HEYES': 81,
  'Jack VAN POORTVLIET': 82, 'Nick TOMPKINS': 81, 'Tom JORDAN': 81,
  'Finn RUSSELL': 89, 'Sam UNDERHILL': 84, 'Ben SPENCER': 82,
  'Thomas DU TOIT': 85, 'Santiago CARRERAS': 82, 'Guido PETTI': 81,
  // URC — Irlande
  'Caelan DORIS': 91, 'Dan SHEEHAN': 90, 'Tadhg FURLONG': 86,
  'Josh VAN DER FLIER': 86, 'James RYAN': 84, 'Jamison GIBSON-PARK': 87,
  'Sam PRENDERGAST': 83, 'Hugo KEENAN': 84, 'Garry RINGROSE': 85,
  'Tadhg BEIRNE': 87, 'Andrew PORTER': 85, 'Jack CROWLEY': 82,
  'Rieko IOANE': 86, 'Bundee AKI': 84, 'Len IKITAU': 85,
  // URC — Écosse / Galles
  'Zander FAGERSON': 84, 'Huw JONES': 83, 'Sione TUIPULOTU': 85,
  'Duhan VAN DER MERWE': 85, 'George HORNE': 82, 'Jack DEMPSEY': 82,
  'Kyle STEYN': 81, 'Rory DARGE': 84, 'Jac MORGAN': 84,
  'Aaron WAINWRIGHT': 82, 'Tomos WILLIAMS': 83, 'Josh ADAMS': 81,
  'Angus BELL': 84,
  // URC — Afrique du Sud
  'Handré POLLARD': 88, 'Kurt-Lee ARENDSE': 86, 'Canan MOODIE': 85,
  'Wilco LOUW': 83, 'Marco VAN STADEN': 83, 'Eben ETZEBETH': 90,
  'Siya KOLISI': 86, 'Damian WILLEMSE': 84, 'Frans MALHERBE': 84,
  'Vincent TSHITUKA': 82, 'Aphelele FASSI': 84, 'Makazole MAPIMPI': 83,
  'Bongi MBONAMBI': 84, 'André ESTERHUIZEN': 85, 'Grant WILLIAMS': 84,
  // Japan Rugby League One
  'Cheslin KOLBE': 90, 'Malcolm MARX': 91, 'Pieter-Steph DU TOIT': 90,
  'Damian DE ALLENDE': 85, 'Jesse KRIEL': 85, 'Kwagga SMITH': 83,
  'Michael LEITCH': 82, 'Kazuki HIMENO': 83, 'Sam CANE': 84,
  'Bernard FOLEY': 78, 'Aaron SMITH': 84, 'Pablo MATERA': 85,
  'Franco MOSTERT': 83, 'Jasper WIESE': 83, 'Lukhanyo AM': 85,
  'Manie LIBBOK': 82,
};

// La table ci-dessus vient de l'ancien export LNR, qui écrivait les prénoms en
// entier (« Grégory ALLDRITT ») ; `base_rugby_finale.json` utilise le prénom
// d'usage (« Greg ALLDRITT »). Cette table renomme les clés pour que les deux
// se rejoignent. Le générateur signale toute vedette qui ne trouve personne.
const ALIAS = {
  'Grégory ALLDRITT': 'Greg ALLDRITT',
  'William SKELTON': 'Will SKELTON',
  'Yoram FALATEA MOEFANA': 'Yoram MOEFANA',
  'Levani botia VEIVUKE': 'Levani BOTIA',
  'Benjamin TAMEIFUNA': 'Ben TAMEIFUNA',
  'Georges henri COLOMBE REAZEL': 'Georges-Henri COLOMBE',
  'Tawera KERR BARLOW': 'Tawera KERR-BARLOW',
  'Yoan TANGA MANGENE': 'Yoan TANGA',
  'Paul ALO EMILE': 'Paul ALO-EMILE',
  'Joseph MANU': 'Joey MANU',
  'Jérémy charles WARD': 'Jeremy WARD',
  'Lekima vuda TAGITAGIVALU': 'Lekima TAGITAGIVALU',
  'Selesitino RAVUTAUMADA': 'Selestino RAVUTAUMADA',
  'Alistaire PRICE': 'Ali PRICE',
  'Viliami VUNIPOLA': 'Billy VUNIPOLA',
  'Daniël michael DU PLESSIS': 'Dan DU PLESSIS',
  'Jean-lue DU PREEZ': 'Jean-Luc DU PREEZ',
  'Robert james DU PREEZ': 'Rob DU PREEZ',
  'Juliàn sixto MONTOYA': 'Julián MONTOYA',
  'Harrison PLUMMER': 'Harry PLUMMER',
  'Madosha TAMBWE': 'Madosh TAMBWE',
  'Robert LEOTA': 'Rob LEOTA',
  'Jiuta naqoli WAINIQOLO': 'Jiuta WAINIQOLO',
  'Samuel SIMMONDS': 'Sam SIMMONDS',
  'Josiah meihana MARAKU': 'Josiah MARAKU',
  'Liam robson ALLEN': 'Liam ALLEN',
  'Jean baptiste GROS': 'Jean-Baptiste GROS',
  'Zach yvan MERCER': 'Zach MERCER',
  'Lewis wesley LUDLAM': 'Lewis LUDLAM',
  'Juan ignacio BREX': 'Ignacio BREX',
  'David george RIBBANS': 'David RIBBANS',
  'Benjamin WHITE': 'Ben WHITE',
  'William COLLIER': 'Will COLLIER',
  'Jake aron MCINTYRE': 'Jake MCINTYRE',
  'Jacobus VAN TONDER': 'Jaco VAN TONDER',
  'Lachlan william SWINTON': 'Lachlan SWINTON',
  'Jonathan GRAY': 'Jonny GRAY',
  'Simione KURUVOLI': 'Simi KURUVOLI',
  'Millenium SANERIVI': 'Mills SANERIVI',
  'David CHERRY': 'Dave CHERRY',
  'Johan georg WASSERMAN': 'Johan WASSERMAN',
  'Christian james JUDGE': 'Christian JUDGE',
  'James SHILLCOCK': 'Jamie SHILLCOCK',
  'Vakhtang ABDALADZE': 'Vakh ABDALADZE',
  'Etonia durugalo BAINIVALU': 'Eto BAINIVALU',
  'Kapeliele PIFELETI JR': 'Kapeli PIFELETI JR',
  'Sione langi VAILANU': 'Sione VAILANU',
  'Ratu leone ROTUISOLIA': 'Leone ROTUISOLIA',
  'Jack william WALSH': 'Jack WALSH',
  'Samuel DAVIES': 'Sam DAVIES',
  'Federico ignacio LAVANINI': 'Federico LAVANINI',
  'Malakai fonokalafi FEKITOA': 'Malakai FEKITOA',
  'Santiago SOCINO': 'Santi SOCINO',
  'Caleb kalisi TIMU': 'Caleb TIMU',
  'Benjamin BOTICA': 'Ben BOTICA',
  'Matthew BEUKEBOOM': 'Matt BEUKEBOOM',
  'Eoghan gerard MASTERSON': 'Eoghan MASTERSON',
  "Benjamin O'DONNELL": "Ben O'DONNELL",
  'Jean baptiste BARRERE': 'Jean-Baptiste BARRÈRE',
  'Charles MATTHEWS': 'Charlie MATTHEWS',
  'Ratu osea WAQANINAVATU': 'Osea WAQANINAVATU',
  'Aaron GRANDIDIER-NKANANG': 'Aaron GRANDIDIER',
  'Bastien VERGNES TAILLEFER': 'Bastien VERGNES-TAILLEFER',
  'Etene NANAI SETURO': 'Etene NANAI-SETURO',
  'Martin PAGE RELO': 'Martin PAGE-RELO',
  'Rodrigo DE BIVAR WEINHOLTZ CARDOSO MARTA': 'Rodrigo MARTA',
  'Dany PRISO MOUANGUE': 'Dany PRISO',
  'Santiago ARATA PERRONE': 'Santiago ARATA',
  'Elias jack GOODHUE': 'Jack GOODHUE',
  'Thomas STANIFORTH': 'Tom STANIFORTH',
  'Fergus LEE WARNER': 'Fergus LEE-WARNER',
  'Martin ALONSO MUÑOZ': 'Martin ALONSO',
  'Baptiste COULLOUD': 'Baptiste COUILLOUD',
  'Ronald PIETERS': 'Juun PIETERS',
  'Gabriel NGANDEBE': "Gabriel N'GANDEBE",
  'Pone FAAMAUSILI': "Pone FA'AMAUSILI",
  'Dalton PAPALII': "Dalton PAPALI'I",
  'Abraham PAPALII': "Abraham PAPALI'I",
};

const brut = { ...VEDETTES_FRANCE, ...VEDETTES_MONDE };
const VEDETTES = {};
for (const [nom, note] of Object.entries(brut)) VEDETTES[ALIAS[nom] ?? nom] = note;

module.exports = { VEDETTES };
