import { agirCarriere, avancerCarriere, creerCarriere } from '../src/lib/ligue/carriere';

const depart = Date.parse('2026-09-07T10:00:00.000Z');
let etat = creerCarriere({ id: 'objectifs-par-match', nom: 'Ligue test', code: 'DR-TEST', compteId: 'a', pseudo: 'Alice', clubNom: 'Club Alice', rythme: 1, maxClubs: 4 }, depart, 'test');
etat = agirCarriere(etat, 'b', { type: 'rejoindre', pseudo: 'Benoit', clubNom: 'Club Benoit' }, depart, 'rejoindre');
etat = agirCarriere(etat, 'a', { type: 'demarrerSaison' }, depart, 'demarrer');
const club = etat.clubs[0];
const avant = etat.objectifs.filter(o => o.clubId === club.id);
if (avant.length !== 4 || !avant.some(o => o.type === 'participer') || !avant.some(o => o.type === 'packs')) throw new Error('Objectifs du premier match absents');
const packGratuit = club.packsGratuits?.[0];
if (!packGratuit) throw new Error('Pack quotidien absent');
etat = agirCarriere(etat, 'a', { type: 'ouvrirPackGratuit', attributionId: packGratuit.id }, depart, 'pack-test');
if (etat.transactions.filter(t => t.clubId === club.id && t.nature === 'objectif' && t.libelle === 'Ouvrir un pack').length !== 1) throw new Error('Objectif de pack non versé immédiatement');
const premiere = etat.rencontres.find(r => r.domicile === club.id || r.exterieur === club.id)!;
etat = avancerCarriere(etat, Date.parse(premiere.ferme) + 2 * 3600_000, 'premier-match');
const apres = etat.objectifs.filter(o => o.clubId === club.id);
if (!premiere || !etat.rencontres.some(r => r.id === premiere.id && r.resultat)) throw new Error('Premier match non joué');
if (apres.length !== 4 || apres.some(o => avant.some(a => a.id === o.id))) throw new Error('Objectifs non renouvelés après le match');
if (!apres.some(o => o.type === 'packGratuit')) throw new Error('Objectif de pack quotidien absent du second match');
const autrePack = etat.clubs[0].packsGratuits?.[0];
if (!autrePack) throw new Error('Second pack quotidien absent');
etat = agirCarriere(etat, 'a', { type: 'ouvrirPackGratuit', attributionId: autrePack.id }, Date.parse(premiere.ferme) + 2 * 3600_000, 'pack-suivant');
if (etat.transactions.filter(t => t.clubId === club.id && t.nature === 'objectif' && t.libelle === 'Ouvrir un pack quotidien').length !== 1) throw new Error('Prime du pack quotidien non versée');
const primes = etat.transactions.filter(j => j.clubId === club.id && j.nature === 'objectif');
if (!primes.some(j => j.ovas === 200)) throw new Error('Prime de participation non versée automatiquement');
const montant = etat.clubs[0].ovas;
etat = avancerCarriere(etat, Date.parse(premiere.ferme) + 2 * 3600_000, 'relecture');
if (etat.clubs[0].ovas !== montant) throw new Error('Prime versée deux fois');
console.log('OK — objectifs de match et de pack renouvelés, primes versées automatiquement une seule fois.');
