import assert from 'node:assert/strict';
import {creerCarriere, agirCarriere, avancerCarriere} from '../src/lib/ligue/carriere';
import {catalogueMondialCarriere, packsBoutiqueDuJour, PACKS_CARRIERE} from '../src/lib/ligue/catalogueCarriere';
import {MS_PAR_MINUTE} from '../src/lib/ligue/matchCarriere';
const now=Date.UTC(2026,8,7);
let e=creerCarriere({id:'test-maj',nom:'Test calendrier',code:'TESTMAJ',compteId:'alice',pseudo:'Alice',clubNom:'Club Alice',rythme:3,maxClubs:32,dotationOvas:12345},now,'test');
assert.equal(e.dotationOvas,12345);assert.equal(MS_PAR_MINUTE,60000);
e=agirCarriere(e,'bob',{type:'rejoindre',pseudo:'Bob',clubNom:'Club Bob'},now,'test');
e=agirCarriere(e,'alice',{type:'demarrerSaison'},now,'test');
const ouvertures=[...new Set(e.rencontres.sort((a,b)=>a.journee-b.journee).map(r=>r.ouvre))];
assert.ok(ouvertures.length>1,'chaque journée doit avoir sa propre date d’ouverture');
const kickoff=Date.parse(e.rencontres[0].ferme);
e=avancerCarriere(e,kickoff,'test');assert.ok(e.rencontres[0].match);assert.equal(e.rencontres[0].match!.termine,false);
e=avancerCarriere(e,kickoff+60000,'test');assert.ok(e.rencontres[0].match!.horloge<2);
const cat=catalogueMondialCarriere();for(const [name,note] of [['Maxime Lucu',93],['Thomas Ramos',93],['Jack Willis',92],['Faf de Klerk',84]] as const){const c=cat.find(c=>c.nom.toLowerCase()===name.toLowerCase());assert.ok(c,name);assert.equal(c.note,note);}
for(const pack of PACKS_CARRIERE)assert.ok(Math.abs(Object.values(pack.probabilites).reduce((a,b)=>a+b,0)-100)<.001,pack.id);
const rayon1=packsBoutiqueDuJour(PACKS_CARRIERE,Date.parse('2026-09-09T12:00:00Z'));
const rayon2=packsBoutiqueDuJour(PACKS_CARRIERE,Date.parse('2026-09-10T12:00:00Z'));
assert.deepEqual(rayon1.slice(0,3).map(p=>p.nom),['Bronze','Argent','Or garanti']);
assert.equal(rayon1.length,5);assert.notDeepEqual(rayon1.slice(3).map(p=>p.id),rayon2.slice(3).map(p=>p.id));
console.log('OK : calendrier daté, Faf de Klerk, horloge réelle et rotation quotidienne de cinq packs.');
