import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { existsSync, unlinkSync } from 'node:fs';
import { classifierFfr, posteFfr } from '../serveur/ffr/classification.js';
import type { ProfilFfr, SourceFfr } from '../serveur/ffr/classification.js';
import { editionProfil, exigerPublication } from '../serveur/ffr/validation.js';
import { genererRegensFfr } from '../src/lib/academieFfr.js';
import { cartesJeunesseARetirer, migrerCartesJeunesse } from '../src/lib/ligue/migrationJeunesse.js';
import { calculateChemistry, collectifCarriere } from '../src/lib/ligue/collectifCarriere.js';
import { catalogueBaseCarriere, catalogueMondialCarriere, carteDepuisSource } from '../src/lib/ligue/catalogueCarriere.js';
import { carteSeniorAutorisee } from '../src/lib/ligue/eligibiliteJoueurs.js';
import { creerCarriere, agirCarriere } from '../src/lib/ligue/carriere.js';
import { serviceFfr } from '../serveur/ffr/contexte.js';
import { stockageFichier } from '../serveur/carriereFichier.js';
import { creerGestionnaireCarriere, empreinteJeton } from '../serveur/carriereApi.js';
import type { ReponseCarriere } from '../serveur/carriereApi.js';
import { echeancesMarche, marcheVide, vueMarchePartage } from '../src/lib/ligue/marchePartage.js';
import { compensationsSoloFfr, migrerCollectionFfr } from '../src/lib/ligue/migrationCollectionFfr.js';
import { normaliserCollectionSolo } from '../src/lib/collectionSolo.js';
import { validerModificationsBoutiqueCompte } from '../src/lib/boutiqueCompte.js';
import { SOURCES_FFR_RETIREES } from '../src/data/protectionFfr.generated.js';
const senior:SourceFfr={ffr_id:1,first_name:'Fixture',last_name:'Senior',sex:'M',category:'Senior',club:'Club X',competition:'Fédérale 1',season:'2025-2026',position:'Centre',matches:12,starts:9};
const p=classifierFfr(senior);assert.equal(p.usage,'MALE_SENIOR_CARD');assert.equal(p.card_status,'ACTIVE_CARD');
for(const category of ['U14','M16','U18','U19','Cadets','Juniors','Crabos'])assert.equal(classifierFfr({...senior,category}).usage,'YOUTH_REGEN_SOURCE');
assert.equal(classifierFfr({...senior,age:17,adult:true}).usage,'YOUTH_REGEN_SOURCE');
assert.equal(classifierFfr({...senior,birth_date:'2009-10-09'}).usage,'YOUTH_REGEN_SOURCE');
assert.equal(classifierFfr({...senior,category:'Espoirs'}).usage,'NEEDS_REVIEW');
assert.notEqual(classifierFfr({...senior,position:undefined}).card_status,'ACTIVE_CARD');
assert.notEqual(classifierFfr({...senior,season:'2020-2021'}).card_status,'ACTIVE_CARD');
assert.equal(classifierFfr({...senior,matches:1}).overall,null);
assert.ok(classifierFfr({...senior,matches:25,starts:24,tries:12}).overall!>classifierFfr({...senior,matches:3,starts:0,tries:0}).overall!);
for(const position of ['Pilier','Talonneur','Deuxième ligne','Troisième ligne','Demi de mêlée','Demi d’ouverture','Centre','Ailier','Arrière'])assert.ok(posteFfr(position),position);
assert.throws(()=>exigerPublication(classifierFfr({...senior,category:'U18'})));
assert.throws(()=>exigerPublication({...p,duplicate:true}));
assert.throws(()=>editionProfil(p,{overall:101}));
assert.equal(editionProfil(p,{sex:'F',category:'U18',birth_date:'2015-01-01'}).gender,'male');
const regens=genererRegensFfr('Club X','one',75);assert.deepEqual(regens,genererRegensFfr('Club X','one',75));
assert.ok(regens.every(r=>r.fictional&&r.potential>=r.overall&&r.developmentCurve.length===6&&!('ffr_id' in r)&&!('photo' in r)));
const base=catalogueBaseCarriere();assert.ok(base.every(c=>carteSeniorAutorisee(c)));
const withdrawnKey=SOURCES_FFR_RETIREES[0].replace('.','-');
assert.equal(normaliserCollectionSolo({quantites:{[withdrawnKey]:3}}).quantites[withdrawnKey],undefined);
assert.equal(validerModificationsBoutiqueCompte({collectionSolo:{quantites:{[withdrawnKey]:3},packsOuverts:{},doublons:2,revision:0}})!.collectionSolo!.quantites[withdrawnKey],undefined);
const oldSolo={...base[0],sourceId:'retired-fixture',note:30};
const equivalents=compensationsSoloFfr([oldSolo],base,new Set([oldSolo.sourceId]));
const [oldKey,equivalent]=[...equivalents][0];assert.ok(equivalent.genApres>=equivalent.genAvant);
const soloMigration=migrerCollectionFfr({quantites:{[oldKey]:3,[equivalent.cle]:2},packsOuverts:{bronze:5},doublons:3,revision:4},equivalents);
assert.equal(soloMigration.collection.quantites[equivalent.cle],5);assert.equal(soloMigration.collection.revision,5);
assert.deepEqual(migrerCollectionFfr(soloMigration.collection,equivalents),{collection:soloMigration.collection,log:[]});
const male=carteDepuisSource(base[0],'fixture','club',1),female={...male,id:'female',gender:'female' as const,clubReel:male.clubReel.toUpperCase(),countryId:male.nation==='France'?'FR':undefined};
assert.ok(calculateChemistry(male,female).sameClub);assert.ok(calculateChemistry(male,female).sameNation);
assert.ok(collectifCarriere([male,female],{titulaires:[male.id,female.id]}).total>0);
assert.ok(!carteSeniorAutorisee(female));assert.ok(carteSeniorAutorisee(female,'women'));assert.ok(carteSeniorAutorisee(female,'mixed'));
const state=creerCarriere({id:randomUUID(),nom:'Fixture',code:'DR-FIXTURE',compteId:randomUUID(),pseudo:'Fixture',clubNom:'Fixture club',rythme:1,maxClubs:2},Date.now(),'fixture-seed');
const original=state.cartes[0],oldId=original.id;original.age=16;original.nom='Identité mineure fixture';original.photo='https://example.test/private.webp';
state.ventes.push({id:'sale',carteId:oldId,vendeurId:original.proprietaire!,type:'enchere',prix:100,expireLe:'2099-01-01',etat:'ouverte',enchere:{clubId:original.proprietaire!,montant:125}});
const soldeAvant=state.clubs[0].ovas,adulteVerrouille=state.cartes[1];adulteVerrouille.verrou='trade';original.verrou='trade';
state.echanges.push({id:'trade',de:original.proprietaire!,vers:'another',cartesDonnees:[oldId,adulteVerrouille.id],cartesDemandees:[],ovasDonnes:75,ovasDemandes:0,etat:'propose',expireLe:'2099-01-01'});
assert.equal(cartesJeunesseARetirer(state).length,1);migrerCartesJeunesse(state,Date.now());
assert.equal(state.cartes.find(c=>c.id===oldId)!.retiree,true);assert.equal(state.ventes[0].etat,'annulee');assert.equal(state.echanges[0].etat,'annule');
assert.equal(adulteVerrouille.verrou,undefined);assert.equal(state.clubs[0].ovas,soldeAvant+125+75,'Les deux réserves distinctes sont restituées une seule fois.');
assert.ok(state.cartes.some(c=>c.origine==='formation'&&c.sourceId.startsWith('regen:')));
assert.equal(state.cartes.find(c=>c.id===oldId)!.photo,undefined);const count=state.cartes.length;migrerCartesJeunesse(state,Date.now());assert.equal(state.cartes.length,count);
const market=marcheVide(1);market.annonces.push({id:'withdrawn',carte:{...male,age:16},vendeur:{ligueId:state.id,clubId:'club',pseudo:'x',nom:'x',division:1},type:'directe',prix:100,expireLe:'2099-01-01',etat:'ouverte'});
assert.equal(vueMarchePartage(market,1,state.id,Date.now()).ventes.length,0);assert.ok(echeancesMarche(market,Date.now()));assert.equal(market.annonces.length,0);
const claimed=marcheVide(1);claimed.annonces.push({id:'partial-fixture',vendeur:{ligueId:state.id,clubId:'seller',pseudo:'Fixture',nom:'Fixture',division:1},carte:{...original,age:16},type:'directe',prix:100,publieLe:'2026-01-01',expireLe:'2099-01-01',etat:'reclamee',acheteur:{ligueId:state.id,clubId:'buyer',pseudo:'Fixture',nom:'Fixture',division:1,montant:100,le:'2026-01-01',solde:true}});
assert.equal(echeancesMarche(claimed,Date.now()),false);assert.equal(claimed.annonces.length,1);assert.equal(claimed.remboursements.length,0,'Une vente partiellement soldée ne rembourse jamais sans rapprocher les deux ligues.');
const file='.ffr/verification-carriere.json';if(existsSync(file))unlinkSync(file);
const storage=stockageFichier(file),kiriId=randomUUID(),guestId=randomUUID();
await storage.creerCompte({id:kiriId,identifiant:'kiri',pseudo:'Owner'});await storage.creerCompte({id:guestId,identifiant:'guest',pseudo:'kiri'});
await storage.ouvrirSession(empreinteJeton('kiri-token'),kiriId,Date.now()+60000);await storage.ouvrirSession(empreinteJeton('guest-token'),guestId,Date.now()+60000);
const fixtures:ProfilFfr[]=base.filter(c=>c.note<50).slice(0,5000).map((c,i)=>classifierFfr({...senior,ffr_id:500000+i,sex:'F',first_name:'Fixture',last_name:String(i),position:c.poste,competition:'Régionale 3'}));
storage.joueurs={acces:async id=>id===kiriId,rechercher:async()=>({joueurs:[],next:null,version:'test'}),catalogue:async gender=>({version:'test',revision:'1',joueurs:gender==='female'?fixtures:[]}),decider:async()=>{},rapport:async()=>({version:'test'})};
const service=serviceFfr(storage.joueurs);await service.avecPool('women',()=>assert.ok(catalogueMondialCarriere().every(c=>c.gender==='female')));
assert.ok(catalogueMondialCarriere().every(c=>c.gender!=='female'));
await service.avecPool('mixed',()=>assert.ok(catalogueMondialCarriere().some(c=>c.gender==='female')));
const api=creerGestionnaireCarriere(storage);
async function request(token:string,url:string,body?:unknown){let status=0,data:any;const res:ReponseCarriere={status(code){status=code;return res;},setHeader(){},json(value){data=value;}};
  await api.handler({method:body?'POST':'GET',url,body,headers:{cookie:`destiny_carriere=${token}`,'content-type':'application/json',host:'localhost'}},res);return {status,data};}
const cleRetiree=SOURCES_FFR_RETIREES[0].replace('.', '-');
const coffreAvant={ovas:0,inventaire:['classique'],skinActif:'classique',equipements:[],equipementActif:{},traitsDebloques:[],collectionSolo:{quantites:{[cleRetiree]:7},packsOuverts:{},doublons:6,revision:1}};
await storage.sauvegarderBoutique(guestId,coffreAvant);
assert.equal((await request('guest-token','/api/carriere',{action:'sauvegarderBoutique',boutique:{...coffreAvant,collectionSolo:normaliserCollectionSolo(coffreAvant.collectionSolo)}})).status,409);
assert.equal((await storage.boutique(guestId))?.collectionSolo.quantites[cleRetiree],7,'Les exemplaires restent disponibles pour leur compensation avant la migration.');
assert.equal((await request('guest-token','/api/carriere?baseJoueurs=1&gender=female')).status,404);
// 9 octobre 2026 : les ligues féminines et mixtes sont ouvertes à tous les comptes (`POOLS_FEMININS_OUVERTS`). Seule la
// Base joueurs du Labo reste réservée à l'autorisation serveur.
const invitee=await request('guest-token','/api/carriere',{action:'creer',playerPool:'women',nom:'Women',clubNom:'Club',rythme:1,maxClubs:2});assert.equal(invitee.status,201,JSON.stringify(invitee.data));
assert.ok(invitee.data.cartes.every((c:any)=>c.gender==='female'),'Une ligue féminine ne distribue que des joueuses, quel que soit le compte.');
const mixte=await request('guest-token','/api/carriere',{action:'creer',nom:'Mixte',clubNom:'Club mixte',rythme:1,maxClubs:2});assert.equal(mixte.status,201,JSON.stringify(mixte.data));
assert.equal(mixte.data.playerPool,'mixed','Sans précision, une ligue est mixte.');
// Ligue mixte : un pack par championnat féminin ; le créateur referme la ligue sur les joueurs (aucune joueuse distribuée), puis la rouvre.
assert.ok(mixte.data.packs.some((p:any)=>p.id.startsWith('womens:')),'Une ligue mixte propose les packs de championnat féminin.');
const commander=(jeton:string,ligue:string,commande:object)=>request(jeton,'/api/carriere',{action:'commande',ligue,requeteId:randomUUID(),commande});
// La dotation d'une ligue mixte peut contenir des joueuses : la refermer sur les joueurs n'est permis que s'il n'y en a aucune.
const aDesJoueuses=mixte.data.cartes.some((c:any)=>c.gender==='female');
const fermee=await commander('guest-token',mixte.data.id,{type:'reglerPool',pool:'men'});
if(aDesJoueuses)assert.notEqual(fermee.status,200,'Une ligue dont un club a des joueuses ne se referme pas sur les joueurs.');
else{
  assert.equal(fermee.data.playerPool,'men');assert.ok(!fermee.data.packs.some((p:any)=>p.id.startsWith('womens:')),'Une ligue masculine n’a plus de pack féminin.');
  const rouverte=await commander('guest-token',mixte.data.id,{type:'reglerPool',pool:'mixed'});assert.equal(rouverte.data.playerPool,'mixed');
  assert.ok(rouverte.data.packs.some((p:any)=>p.id.startsWith('womens:')));
}
// Une ligue féminine dont les clubs ont des joueuses ne se referme pas sur les joueurs, mais s'ouvre au mixte.
assert.notEqual((await commander('guest-token',invitee.data.id,{type:'reglerPool',pool:'men'})).status,200);
assert.equal((await commander('guest-token',invitee.data.id,{type:'reglerPool',pool:'mixed'})).data.playerPool,'mixed');
assert.notEqual((await commander('kiri-token',mixte.data.id,{type:'reglerPool',pool:'men'})).status,200,'Seul le créateur règle le genre de sa ligue.');
assert.equal((await request('kiri-token','/api/carriere?baseJoueurs=1')).status,200);
const publicCatalogue=await request('guest-token','/api/carriere?catalogueSolo=1');assert.equal(publicCatalogue.status,200);
assert.ok(publicCatalogue.data.ffr.some((c:any)=>c.gender==='female'), 'La collection publique reçoit les joueuses seniors approuvées.');
const created=await request('kiri-token','/api/carriere',{action:'creer',playerPool:'women',nom:'Women test',clubNom:'Club test',rythme:1,maxClubs:2});assert.equal(created.status,201,JSON.stringify(created.data));
assert.ok(created.data.cartes.every((c:any)=>c.gender==='female'));const leagueId=created.data.id,code=created.data.code;
// Sans y être inscrit, on ne lit ni ne joue dans la ligue d'un autre ; avec son code, on la rejoint comme n'importe quelle ligue.
assert.notEqual((await request('guest-token',`/api/carriere?ligue=${leagueId}&v=1`)).status,200);
assert.notEqual((await request('guest-token','/api/carriere',{action:'commande',ligue:leagueId,requeteId:randomUUID(),commande:{type:'ouvrirPack',packId:'bronze'}})).status,200);
const rejointe=await request('guest-token','/api/carriere',{action:'rejoindre',code,clubNom:'Club invite'});assert.ok(rejointe.status===200||rejointe.status===201,JSON.stringify(rejointe.data));
const opened=await request('kiri-token','/api/carriere',{action:'commande',ligue:leagueId,requeteId:randomUUID(),commande:{type:'ouvrirPack',packId:'bronze'}});assert.equal(opened.status,200,JSON.stringify(opened.data));
assert.ok(opened.data.cartes.every((c:any)=>c.gender==='female'));
// No role or flag is inferred from a display name, even when the guest calls itself Kiri.
assert.equal((await storage.joueurs.acces(guestId)),false);
const normal=agirCarriere(state,state.clubs[0].compteId,{type:'actualiser'},Date.now(),'test');assert.ok(normal.migrationsFfr?.length);
console.log('FFR : classification, notation, confidentialité, migration idempotente, collectif mixte, packs féminins et autorisation backend validés.');
