-- LE CLASSEMENT MONDIAL — schéma pour Vercel + Postgres (Neon)
--
-- À coller UNE FOIS dans la console SQL de la base (Vercel → Storage → ta base
-- → Query, ou le SQL Editor de Neon). Voir `serveur/VERCEL.md` pour le pas à pas.
--
-- ⚠️ V2 — LA BASE GARDE MAINTENANT LA FICHE, PAS SEULEMENT LE SCORE.
-- La v1 ne stockait que `pseudo` + `score` (demande d'alors : « dans la DB je
-- veux retenir juste le score »), et notait la conséquence : « on ne pourra
-- pas, plus tard, afficher 12 saisons, 44 essais à côté d'un score ». C'est
-- exactement ce qui est demandé aujourd'hui — « dans le classement mondial,
-- qu'on puisse voir les stats des autres joueurs, leurs profils, armoires à
-- trophées, clubs qu'ils ont faits ». On conserve donc les faits AFFICHABLES,
-- ceux-là mêmes qui servent au recalcul : rien de nominatif, rien de personnel,
-- et le pseudo reste choisi par le joueur.
--
-- ⚠️ LA SÉCURITÉ NE CHANGE PAS D'UN POUCE. Ce qui protège le classement, c'est
-- que le serveur RECALCULE le score (`scoreDeLaFiche`) au lieu de croire celui
-- qu'on lui envoie. Stocker davantage n'ouvre aucune brèche : chaque champ est
-- borné par `verifierFiche` avant d'arriver ici.
--
-- ═══ MIGRATION D'UNE BASE V1 DÉJÀ EN LIGNE ═══════════════════════════════════
-- À coller tel quel : les colonnes sont nullables, les lignes existantes
-- restent affichables (score seul, fiche vide) et se complètent au prochain
-- envoi du joueur.
--
--   alter table classement
--     add column if not exists nom        text,
--     add column if not exists poste      text,
--     add column if not exists nation     text,
--     add column if not exists age        integer,
--     add column if not exists saisons    integer,
--     add column if not exists note       integer,
--     add column if not exists reputation integer,
--     add column if not exists matchs     integer,
--     add column if not exists essais     integer,
--     add column if not exists selections integer,
--     add column if not exists titres     jsonb,
--     add column if not exists clubs      jsonb;
--
-- ═══ MIGRATION V3 : UNE LIGNE PAR JOUEUR, PLUS PAR PSEUDO ═══════════════════
-- ⚠️ C'EST LA CORRECTION D'UN BUG SIGNALÉ EN JEU : « si on a le même pseudo
-- qu'un joueur dans le classement, notre classement apparaît pas ».
--
-- Le pseudo était la CLÉ PRIMAIRE. Deux joueurs qui choisissent le même nom se
-- partageaient donc UNE ligne, et l'écriture est gardée par « le score ne
-- recule pas » : celui des deux qui avait le score le plus bas n'écrivait
-- RIEN — sans erreur, sans message, le serveur répondant « ok ». Sa carrière
-- n'entrait jamais au classement, et rien à l'écran ne pouvait l'expliquer.
--
-- Deux colonnes règlent ça :
--   `cle` — l'identité de l'INSTALLATION qui envoie (tirée au hasard une fois,
--           rangée dans la sauvegarde du joueur). C'est elle qui porte
--           désormais l'unicité, et elle ne sort JAMAIS du serveur : c'est le
--           droit d'écrire sur cette ligne.
--   `id`  — l'identifiant PUBLIC de la ligne, renvoyé par le GET. Il permet à
--           l'écran d'afficher deux lignes de même pseudo sans les confondre,
--           et au joueur de reconnaître la sienne.
--
-- ⚠️ LES LIGNES EXISTANTES GARDENT LEUR IDENTITÉ HÉRITÉE (`v1:<pseudo>`), et
-- on n'en supprime aucune. Conséquence assumée, à dire franchement : un joueur
-- qui figurait au classement AVANT cette migration ouvrira une nouvelle ligne à
-- son prochain envoi, et sa ligne héritée restera à côté. Le nettoyage se fait
-- à la main si on le souhaite, jamais par le serveur — effacer une ligne sur la
-- foi d'un pseudo, c'est exactement le raisonnement qui a créé le bug.
--
--   alter table classement add column if not exists cle text;
--   alter table classement add column if not exists id bigint generated by default as identity;
--   update classement set cle = 'v1:' || pseudo where cle is null;
--   alter table classement alter column cle set not null;
--   alter table classement drop constraint if exists classement_pkey;
--   alter table classement add constraint classement_pkey primary key (id);
--   create unique index if not exists classement_cle_idx on classement (cle);
--
-- Pour vérifier qu'elle est passée :
--   select id, cle, pseudo, score from classement order by score desc limit 5;
--
-- ⚠️ TANT QU'ELLE N'EST PAS JOUÉE, LE JEU CONTINUE : `api/classement.ts`
-- détecte l'absence des colonnes (code Postgres 42703), le journalise, et
-- retombe sur l'écriture par pseudo — donc sur l'ancien comportement, bug
-- compris. Rien ne casse, mais rien n'est corrigé non plus.

-- ⚠️ DIFFÉRENCE AVEC `schema.sql` (la version Supabase) : PAS DE ROW LEVEL
-- SECURITY, et c'est volontaire. Sur Supabase, le navigateur parle directement
-- à la base avec une clé publique — il FAUT donc une politique qui lui interdise
-- d'écrire. Ici, la chaîne de connexion vit dans les variables d'environnement
-- de la fonction Vercel : le navigateur n'a aucun accès à la base, jamais. La
-- surface est plus petite, il y a moins à verrouiller.

create table if not exists classement (
  -- L'identifiant PUBLIC de la ligne : c'est lui que le GET renvoie et que
  -- l'écran utilise pour distinguer deux carrières au même pseudo.
  id       bigint generated by default as identity primary key,
  -- ⚠️ L'IDENTITÉ DE L'INSTALLATION QUI ENVOIE — une seule ligne par joueur,
  -- donc pas de spam, et surtout PLUS DE COLLISION ENTRE HOMONYMES. Elle ne
  -- sort jamais du serveur : c'est le droit d'écrire sur cette ligne.
  -- Voir la section « MIGRATION V3 » en tête pour le pourquoi.
  cle      text not null unique check (length(cle) between 1 and 40),
  -- Le pseudo n'est plus qu'un LIBELLÉ : deux joueurs peuvent porter le même.
  pseudo   text not null check (length(pseudo) between 1 and 24),
  -- ⚠️ Le plafond vient de `SCORE_MAX` (src/lib/classementMondial.ts) : la
  -- carrière théorique maximale du jeu. Une valeur au-dessus est
  -- mathématiquement impossible — la base elle-même la refuse, même si le code
  -- se trompait. Il a changé deux fois : 64 488 → 82 488 quand les distinctions
  -- individuelles sont arrivées (4 → 9 titres par saison), puis 82 488 → 117 000
  -- quand `noteMax` est passé de 99 à 100 (le serveur refusait de vraies
  -- carrières : « note hors bornes (100, attendu 0..99) »). Si tu retouches
  -- `LIMITES`, remets cette valeur à jour, sinon la base rejettera des scores
  -- que le jeu produit. `npx vite-node scripts/verifClassement.ts` l'affiche.
  --
  -- Sur une base déjà en ligne :
  --   alter table classement drop constraint if exists classement_score_check;
  --   alter table classement add constraint classement_score_check
  --     check (score >= 0 and score <= 123100);
  -- ⚠️ TROISIÈME DÉPLACEMENT : le mode manager ajoute un second barème, et
  --    une carrière « joueur + entraîneur » cumule les deux versants.
  --    82 500 → 117 000. Sur une base déjà en ligne :
  --      alter table classement drop constraint classement_score_check;
  --      alter table classement add constraint classement_score_check
  --        check (score >= 0 and score <= 123100);
  score    integer not null check (score >= 0 and score <= 123100),
  cree_le  timestamptz not null default now(),
  maj_le   timestamptz not null default now(),

  -- ═══ LA FICHE AFFICHABLE (v2) ═════════════════════════════════════════════
  -- Les mêmes champs que ceux qui servent au recalcul du score, plus les clubs.
  -- TOUS NULLABLES : une ligne écrite par la v1 reste lisible, elle n'affiche
  -- simplement pas de détail tant que le joueur n'a pas renvoyé sa carrière.
  nom        text,
  poste      text,
  nation     text,
  age        integer,
  saisons    integer,
  note       integer,
  reputation integer,
  matchs     integer,
  essais     integer,
  selections integer,
  -- Ids de trophées (`data/trophees.ts`) et clubs traversés, dans l'ordre.
  titres     jsonb,
  clubs      jsonb
);

create index if not exists classement_score_idx on classement (score desc);

-- ═══════════════════════════════════════════════════════════════════════════
-- LE GARDE-FOU DE DÉBIT
-- ═══════════════════════════════════════════════════════════════════════════
-- Une carrière crédible demande des heures de jeu. Un envoi par heure et par
-- appareil rend le forçage brutal inutile. On ne garde qu'un HACHÉ de
-- l'identifiant d'appareil : jamais l'IP en clair, jamais rien de nominatif.
create table if not exists envois (
  appareil  text not null,
  envoye_le timestamptz not null default now()
);
create index if not exists envois_appareil_idx on envois (appareil, envoye_le desc);

-- Purge : on ne garde pas d'historique au-delà de ce qui sert au débit.
-- Deux jours suffisent (la fenêtre la plus longue est de 24 h). À planifier une
-- fois par jour — Vercel Cron (`vercel.json`), pg_cron, ou à la main.
-- delete from envois where envoye_le < now() - interval '2 days';
